stages:
    - build

build:
    stage: build
    tags: 
        - shyft
        
    script:
        - "echo Using ${SHYFT_DEPENDENCIES_DIR}"
        - "echo Path ${PATH}"
        - "mkdir -p build"
        - "cd build&&cmake .."
        - "make -j 4 VERBOSE=0"
        - make install
        - make test
        - ". activate shyft_env"
        - 'PYTHONPATH=.. python -c"import shyft; shyft.print_versions()"'
        - "PYTHONPATH=.. nosetests ../shyft/tests --with-coverage --cover-package=shyft.repository --cover-package=shyft.orchestration --cover-package=shyft.api"

