stages:
    - build
    - cpp_test
    - py_test

build:
    stage: build
    tags: 
        - shyft
        
    script:
        - "echo Using ${SHYFT_DEPENDENCIES_DIR}"
        - "echo Path ${PATH}"
        - "mkdir -p build"
        - "cd build&&cmake .."
        - "make -j 4 VERBOSE=1"
        - make install
    
cpp_test:
    stage: cpp_test
    tags: 
        - shyft
    dependencies:
        - build
    script:
        - "cd build && make test"

py_test:
    stage: py_test
    tags: 
        - shyft
    dependencies:
        - build
    script: # TODO: add python tests here
        - exit 0
        


