version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - apt-get update -y
      - apt-get install -y build-essential liblapack-dev libblas-dev libatlas-base-dev libpng-dev
      - apt-get install -y g++-8 gcc-8 gfortran
      - wget -O ../cmake.install.sh https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.sh
      - bash ../cmake.install.sh --skip-license --prefix=/usr
      - echo pwd is `pwd`,$HOME
      - export CXX="g++-8" CC="gcc-8"
      - bash build_support/build_dependencies.sh

  build:
    commands:
      - export CXX="g++-8" CC="gcc-8"
      - export BROOT=`pwd`
      - export PATH=${BROOT}/../miniconda/bin:$PATH
      - export LD_LIBRARY_PATH=${BROOT}/../shyft_dependencies/lib
      - mkdir -p build
      - cd build&&cmake ..
      - make -j 3 VERBOSE=1   CXX="g++-8" CC="gcc-8"
      - make install


  post_build:
    commands:
      - export BROOT=${BROOT:-`pwd`}
      - echo $BROOT
      - min_conda=${BROOT}/../miniconda
      - export PATH=${min_conda}/envs/shyft_env/bin:${min_conda}/bin:$PATH
      - export LD_LIBRARY_PATH=${BROOT}/../shyft_dependencies/lib
      - export CONDA_PYTHON_EXE=${min_conda}/bin/python
      - export CONDA_EXE=${min_conda}/bin/conda
      - export CONDA_DEFAULT_ENV=shyft_env
      - export CONDA_SHLVL=1
      - export _CONDA_SET_PROJ_LIB=PROJ_LIB
      - export PROJ_LIB=${min_conda}/envs/shyft_env/share/proj
      - make test
      - PYTHONPATH=.. python -c"import shyft; shyft.print_versions()"
      - nosetests ../shyft/tests --with-coverage --cover-package=shyft.repository --cover-package=shyft.orchestration --cover-package=shyft.api


      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
    